add gateway_ip attribute in restore script

diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,3 +1,75 @@
+#!/bin/bash                                                                                                                                    
+                                                                                                                                               
+DB_NAME="outreach"
+DB_PASS="root"
+VERSION="v2.0.9"
+APP_URL="http://localhost/nodalcentres"
+GOOGLE_API_KEY="paste-geocode-api-key-here"
+
+BACKUP_FILE=$1
+
+usage() {
+  echo "Usage:"
+  echo "$0 <path/to/the/backup/file.tar>"
+}
+
+if [ -z $BACKUP_FILE ]; then
+  echo "Error: No arguments were passed!!"
+  echo "Error: The path to the backup file must be passed."
+  usage
+  exit 1;
+fi
+
+# untar the $BACKUP_FILE file                                                                                                                  
+tar -xvf $BACKUP_FILE
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while untaring."
+  echo "Aborting restore."
+  exit 1;
+fi
+
+# restore from the dump folder                                                                                                                 
+mysql -u root -p$DB_PASS -e "drop database $DB_NAME"
+if [ $? -ne 0 ]; then
+  echo "Error: in droping database name $DB_NAME"
+  echo "Aborting"
+
+fi
+
+mysql -u root -p$DB_PASS -e "create database $DB_NAME"
+if [ $? -ne 0 ]; then
+  echo "Error: in droping database name $DB_NAME"
+  echo "Aborting"
+  exit 1;
+fi
+
+mysql -u root -p$DB_PASS $DB_NAME < $DB_NAME.sql
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while restoring db dump."
+  echo "Aborting restore."
+  exit 1;
+fi
+
+mysql -u root -p$DB_PASS $DB_NAME -e "use $DB_NAME; ALTER TABLE workshops add column gateway_ip varchar(20) after date"
+
+
+
+if [ $? -ne 0 ]; then
+  echo "Error: Couldn't add attribute gateway_ip to workshops"
+  echo "Aborting."
+  exit 1;
+else
+    echo "################"
+    echo "Restore successful."
+    echo "###############"
+fi
+exit 0;
+    
+    
+
+
+
+
 #!/bin/bash
 
 DB_NAME="outreach"
